### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by shankar-bavan** [justnixx/laravel-breeze-api-react#2]
I got below error

```
CSRF token mismatch
```

**Comment by ccnixx** [comment]
Hi @shankar-bavan , I couldn't reproduce the error. Could you walk me through how you encountered it? Here's what I did, and I didn't encounter any errors. You can also find screenshots below:

1. I executed git pull.

2. I then opened my code editor.

3. I initiated the backend server by running `php artisan serve`.

4. I initiated the frontend server by running `yarn dev`.

5. Finally, I started the MySQL server (I use DBngin).

![signup](https://github.com/justnixx/laravel-breeze-api-react/assets/45858998/cbdca8a9-c1cf-4036-8348-83341c15fa4f)
![signin](https://github.com/justnixx/laravel-breeze-api-react/assets/45858998/e3846017-c590-4dd2-bed2-0c03ea69e228)
![dash+b4+email+verification](https://github.com/justnixx/laravel-breeze-api-react/assets/45858998/ebe94cd9-e71b-45db-922e-4cf95da86a87)
![dash+after+email+verification](https://github.com/justnixx/laravel-breeze-api-react/assets/45858998/9b09f759-165d-4cf9-b772-f4226c00dd35)

**Comment by shankar-bavan** [comment]
I resolved it. I used http://127.0.0.1:3000 instead of http://localhost:3000
